### ISSUE TITLE
Installation issues / suggestions

### ISSUE THREAD

**Issue by jsrozner** [InSyncWithFoo/pyright-langserver-for-pycharm#15]
Thank you for this! I have gotten it to work and it is awesome. Here are some of the issues I had getting started:
1. I do not see this plugin in the marketplace. I installed from source as you describe in the README
2. I was sure about setting up pyright-langserver. It would be helpful to add something like the following to the README:
	1. ` brew install pyright ` (pip or conda would also work)
	2. point Settings | Tools | Pyright LS (Global) / Pyright LS (Project) to, e.g.  `/opt/homebrew/bin/pyright-langserver` (or the pip installation

**Comment by InSyncWithFoo** [comment]
So, as I understand, there's actually no bug and you got the plugin working? Thanks for using!

As for the Marketplace, it is awaiting approval and is expected to be live tomorrow (2024-04-12) or the day after that. Maybe I shouldn't have pushed that commit so soon, but that happened.

As for the executable, I made sure to link to [the docs](https://insyncwithfoo.github.io/pyright-for-pycharm/) in [the <i>Usage</i> section](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm#usage). You probably didn't see it? I do agree that a how-to-install notice would be a good addition, however.

**Comment by jsrozner** [comment]
Yes, definitely not a bug! Awesome re marketplace - curses of being on the bleeding edge :P 

What I was not sure about was whether pyright-python-langserver was something that came with this plugin (yeah, I'm a noob for this one). I eventually figured I'd probably need to pip or brew install but I tried first just typing pyright-langserver in the settings box (e.g., maybe it comes with pycharm?; maybe it comes with the plugin? Idk!...but having a path to local executable in the end made much more sense). 

Just having that usage line rewritten to be a brew or pip path (and/or mentioning that it's something the user will need to install) would have helped me. 

Thanks again for this plugin

**Comment by InSyncWithFoo** [comment]
For the record, I just received a confirmation a few minutes ago: It is now (officially) [available on the Marketplace](https://plugins.jetbrains.com/plugin/24146).

**Comment by InSyncWithFoo** [comment]
That should be it. I really, <em>really</em> want to avoid duplicating the docs (since I'm already doing everything twice) as well as overloading the description, so I made the link a little bit more explicit/specific and added some notices to the docs instead (sister [412b5ed](https://github.com/InSyncWithFoo/pyright-for-pycharm/commit/412b5eddbcb43d7e8ed44cebfa231d2db958fefa)).
