### ISSUE TITLE
Render restructured/"sphinx" docstrings

### ISSUE THREAD

**Issue by olejorgenb** [InSyncWithFoo/pyright-langserver-for-pycharm#20]
### Feature or enhancement

First - thanks or creating this plugin!

I noticed that docstrings which use the `restructured/"sphinx"` format is not rendered properly in the quick doc dialog. It would be nice if they where.

![image](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/72201/44d56f38-0990-4fda-a375-15c0e35e159b)

### Proposed solution

https://github.com/microsoft/pylance-release/issues/5363 is maybe related? But the plugin could still render based on the raw text. Ideally the plugin would pass the docstring through pycharms own renderer which respect the project setting for docstring format, but I have no idea how hard that would be to implement

**Comment by InSyncWithFoo** [comment]
A while ago I thought about this too, and here's what I discovered so far:

As of yet, the LSP specifications only ever defined [two kinds](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContent) of documentation format: plain text and GitHub-flavored Markdown.

So, this is how a request-and-response pair looks like from the logs when I tried hovering over a function just now:

```log
2024-04-17 16:28:42,684 [ 162587]   FINE - #c.i.p.l.i.c.Lsp4jServerConnector - --> PyrightLSDescriptor@project: {"jsonrpc":"2.0","id":"72","method":"textDocument/hover","params":{"textDocument":{"uri":"file:///project/src/pkg/baz.py"},"position":{"line":2,"character":4}}}
2024-04-17 16:28:42,709 [ 162612]   FINE - #c.i.p.l.i.c.Lsp4jServerConnector - <-- PyrightLSDescriptor@project: {"jsonrpc":"2.0","id":"72","result":{"contents":{"kind":"markdown","value":"```python\n(function) def foo(a: int) -> None\n```\n---\nFoo bar baz qux.\n\n:param a: Lorem ipsum dolor sit amet.  \n:return: Consectetur adipiscing elit."},"range":{"start":{"line":2,"character":4},"end":{"line":2,"character":7}}}}
```

<details>
<summary>File content</summary>

```python
def foo(a: int) -> None:
    """
    Foo bar baz qux.

    :param a: Lorem ipsum dolor sit amet.
    :return: Consectetur adipiscing elit.
    """

    return None
```
</details>

<details>
<summary>Unminified</summary>

```json
{
	"jsonrpc": "2.0",
	"id": "72",
	"method": "textDocument/hover",
	"params": {
		"textDocument": {
		"uri": "file:///project/src/pkg/baz.py"
	},
	"position": {
		"line": 2,
		"character": 4
	}
	}
}
```

```json
{
	"jsonrpc": "2.0",
	"id": "72",
	"result": {
		"contents": {
			"kind": "markdown",
			"value": "```python\n(function) def foo(a: int) -> None\n```\n---\nFoo bar baz qux.\n\n:param a: Lorem ipsum dolor sit amet.  \n:return: Consectetur adipiscing elit."
		},
		"range": {
			"start": {
				"line": 2,
				"character": 4
			},
			"end": {
				"line": 2,
				"character": 7
			}
		}
	}
}
```
</details>

The `contents` property, as received, is already formatted as Markdown (note the code fences, the triple-hyphens and the double-spaces at the end of the second-to-last line):

`````markdown
```python
(function) def foo(a: int) -> None
```
---
Foo bar baz qux.

:param a: Lorem ipsum dolor sit amet.  
:return: Consectetur adipiscing elit.
`````

To make things worse, the property responsible for hover support is just a boolean property, which means I can't just override it with a custom handler like I would with, say, completion support:

```kotlin
abstract class LspServerDescriptor /* ... */ {
  // ...
  /**
   * Whether the IDE should ask the LSP server for hover information by sending the
   * [textDocument/hover](https://microsoft.github.io/language-server-protocol/specification/#textDocument_hover) request.
   */
  open val lspHoverSupport = true

  open val lspCompletionSupport: LspCompletionSupport? = LspCompletionSupport()
  // ...
}
```

**Comment by InSyncWithFoo** [comment]
My conclusion is that this is just not possible at the moment, considering the specifications' own limitations and that the LSP APIs are still experimental.

[Version 0.2.0](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/releases/tag/v0.2.0), which was released earlier today (awaiting approval), will allow you to turn off Pyright's hover support. Of course, that comes with a drawback of not being able to hover a variable to know its type as inferred by Pyright.

Closing this for now, but I'm willing to work on it as soon as I find out a way to do so.
