### ISSUE TITLE
allow language server settings to be configured in the project

### ISSUE THREAD

**Issue by DetachHead** [InSyncWithFoo/pyright-langserver-for-pycharm#23]
### Feature or enhancement

these settings are currently only configurable globally, but it would be useful if they could be configured in the project:

![image](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/57028336/e6db6754-0396-43da-9357-d42eb1f6ea92)

### Proposed solution

support the same settings available globally in the project as well

### Additional context

i want to disable pycharm's awful type checking in favor of pyright's for my team, which ideally would include enabling hover and completion support from the language server. ideally my team shouldn't have to manually configure this themselves and i can instead just commit a config file

**Comment by InSyncWithFoo** [comment]
There's one major problem: What should the plugin do if the global value of a setting is different from that of the project?

If I were to support both levels equally, I would need an extra "undetermined" state for every setting, which is both hard to implement and unintuitive.

P/S: FYI, 0.3.0 will be introducing [many other global language server settings](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/blob/d4814c3/CHANGELOG.md#unreleased).

**Comment by DetachHead** [comment]
> There's one major problem: What should the plugin do if the global value of a setting is different from that of the project?

i would suggest doing what vscode does, which is having project settings take priority over global settings.

> If I were to support both levels equally, I would need an extra "undetermined" state for every setting, which is both hard to implement and unintuitive.

this could be useful in some cases, but i agree that it's probably not worth doing. in vscode, pretty much all settings can be configured either globally or on the project level, with the project settings taking priority, and that works well 99% of the time imo.

**Comment by InSyncWithFoo** [comment]
> [...] having project settings take priority over global settings.

Then the global settings are unnecessary, aren't they?

Take "Hover support" as example:

* Global says that it should be disabled, yet
* Project says it should be enabled (default value).

How would a teammate of yours disable or enable a setting they don't like <em>only for them</em>, if project settings are always preferred? Having an "undetermined" state is not just "worth doing", but necessary for the plugin to know that there are no project override for a given setting.

From a more realistic aspect, here's how [GitToolbox](https://github.com/zielu/GitToolBox) does it: One checkbox for every project-overridable setting.

![](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/122007197/887f3a59-1da8-4214-b6f8-6475d1573bc8)

This is not so nice an example, so if you know a better one I could learn from, I'm all eyes.

**Comment by DetachHead** [comment]
arguably yeah. i personally barely ever use global settings, as each project i work on usually has its own config that you'd want to use in order to match the checks in the project's CI.

i also think some of the settings aren't necessary. for example, are there any cases where you wouldn't want errors to provide a link to the error code? or would you ever want to disable hover support or go to definition? pyright is far better than pycharm's built in type checking, so i don't see why users of this plugin wouldn't want all of its features to be enabled by default.

**Comment by InSyncWithFoo** [comment]
In short, there are limitations. I have to decide on a case-by-case basis, and as you have probably known by now, I'm not a very good decision-maker.

* Hover: See #20. Regardless, it's enabled by default, since knowing what Pyright thinks of a variable's type is important, at least [to me](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/issues/18#issuecomment-2064297599).
* Completion: There might be duplicate suggestions, as seen in [these](https://github.com/InSyncWithFoo/pyright-for-pycharm/blob/bc55d40f6c25209c0d4d25ea75b73fd87ce88ff1/docs/assets/lsp-configurations-demo-server-completion-support-enabled.png) [screenshots](https://github.com/InSyncWithFoo/pyright-for-pycharm/blob/bc55d40f6c25209c0d4d25ea75b73fd87ce88ff1/docs/assets/lsp-configurations-demo-server-auto-import-completions-disabled.png).
* Go-to-definition: This doesn't actually have an immediately recognizable effect, so I disable it by default, but that may still be changed.

**Comment by DetachHead** [comment]
> Completion: There might be duplicate suggestions, as seen in [these](https://github.com/InSyncWithFoo/pyright-for-pycharm/blob/bc55d40f6c25209c0d4d25ea75b73fd87ce88ff1/docs/assets/lsp-configurations-demo-server-completion-support-enabled.png) [screenshots](https://github.com/InSyncWithFoo/pyright-for-pycharm/blob/bc55d40f6c25209c0d4d25ea75b73fd87ce88ff1/docs/assets/lsp-configurations-demo-server-auto-import-completions-disabled.png).

i guess that's because pycharm already has its own autocomplete suggestions. idk if there's a way to disable those without disabling suggestions entirely

> Go-to-definition: This doesn't actually have an immediately recognizable effect, so I disable it by default, but that may still be changed.

potentially the same issue here. since pycharm has its own "go to definition" support, so it's probably difficult to notice when/if pyright is overwriting it with its own definitions

honestly, pycharm's built in type checking is so bad that i wish they'd just scrap it and adopt the pyright language server officially, so a 3rd party plugin isn't even needed. either way, i appreciate your effort on these plugins. i tried making a pyright plugin myself once but i couldn't get it working.

**Comment by InSyncWithFoo** [comment]
> i tried making a pyright plugin myself once but i couldn't get it working.

I can relate to this. [Originally](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/tree/49e1be98468bf67eb6bfd469c861caf18aa51eb0) this plugin was a broken idea. Had it not been for the support I received in #1 and #4, I probably would never have gone so far.

Anyway, I do intend to work on this someday, but no ETA. Closing until I can find a good example.
