### ISSUE TITLE
Add parentheses to autocomplete

### ISSUE THREAD

**Issue by johannesschaffer** [InSyncWithFoo/pyright-langserver-for-pycharm#47]
### Feature or enhancement

The plugin currently completes e.g. functions without adding parentheses. This is more in line with VSCode than Jetbrains IDEs.

### Proposed solution

Align it with how the native PyCharm autocomplete works. E.g. complete "my_func()" instead of "my_func"

**Comment by InSyncWithFoo** [comment]
PyCharm actually has this setting that allows users to have or not have parentheses autocompleted:

![Insert parentheses automatically when applicable](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/assets/122007197/5bd8e5c2-b7f1-4530-b90b-280790a63f7f)

Copying that should be simple enough. I'll get back with a PR in a few hours.

**Comment by InSyncWithFoo** [comment]
Done. Try it out and let me know if there are any problems.

**Comment by InSyncWithFoo** [comment]
> Copying that should be simple enough.

I take that back. It <em>is</em> simple to make it work, but much harder to make it work <em>nicely</em>.

Consider the following example:

```python
def no_args() -> None: ...
def default_arg(v: int = 42) -> None: ...
def args(v: int) -> None: ...

class Foo:

    def no_args(self) -> None: ...
    def default_arg(self, v: int = 42) -> None: ...
    def args(self, v: int) -> None: ...

lambda_no_args = lambda: None
lambda_default_arg = lambda v = 42: None
lambda_args = lambda v: None
lambda_args_with_type: Callable[[int], None] = lambda v: None
```

Here's PyCharm's autocompletions, which know where to put the carets:

```python
copyright()|
print(|)
int|

no_args()|
default_arg(|)
args(|)
Foo|

Foo().no_args()|
Foo().default_arg(|)
Foo().args(|)

Foo.no_args(|)
Foo.default_arg(|)
Foo.args(|)

lambda_no_args|
lambda_default_arg|
lambda_args|
lambda_args_with_type|
```

Meanwhile, Pyright's `textDocument/completion` results are extremely concise, with no signature data whatsoever:

```json5
{
	"result": {
		"items": [
            // ...
			{
				"label": "no_args",
				"kind": 3,  // Function
				"data": {
					"uri": "file:///<project>/file.py",
					"position": { "line": 42, "character": 0 },
					"symbolLabel": "no_args"
				},
				"sortText": "09.9999.no_args"
			},
            // ...
		]
	}
}
```

What I seem to need but don't have access to is the `completionItem/resolve` response, whose corresponding request is only sent if the item is navigated to:

```json5
// completionItem/resolve response
{
	"result": {
		"label": "default_arg",
		"kind": 3,  // Function
		"sortText": "05.0000.default_arg",
		"insertTextFormat": 2,  // Snippet
		"data": {
			"uri": "file:///<project>/file.py",
			"position": { "line": 42, "character": 7 },
			"symbolLabel": "default_arg"
		},
		"documentation": {
			"kind": "markdown",
			"value": "```python\ndef default_arg(v: int = 42) -> None\n```"
		}
	}
}
```

**Comment by johannesschaffer** [comment]
The adding of parentheses isn't very good in VSCode either. It always completes them for functions, classes, ... - e.g. when you use a class as a type or pass afunction as argument it still autocompletes parentheses.So I think you can just look at the type and then always add parentheses

**Comment by InSyncWithFoo** [comment]
> It always completes them for functions, classes, ... - e.g. when you use a class as a type or pass afunction as argument it still autocompletes parentheses.So I think you can just look at the type and then always add parentheses

About that, I originally picked four kinds: `Method`, `Function`, `Constructor` and `Class`. The lattermost of which was removed on a second thought since we are working with type users and `Class` completions happen quite often in type hints. PyCharm seems to agree with this: `int` and `Foo` are both completed with no parentheses, even in normal code flow.

I would really prefer it if we could further mimic PyCharm's behaviour, but perhaps this will do for now.

**Comment by InSyncWithFoo** [comment]
Just FTR, I forgot to mention decorators. PyCharm consistently completes them with no parentheses at all:

```python
@no_arg|
@default_arg|
@args|
```

This will probably be handled by processing the PSI and related information passed via `CompletionParameters`.

**Comment by johannesschaffer** [comment]
@InSyncWithFoo I just noticed it completes function parentheses only when the function is already imported.
