### ISSUE TITLE
Import path instead of Auto-Import

### ISSUE THREAD

**Issue by johannesschaffer** [InSyncWithFoo/pyright-langserver-for-pycharm#49]
### Feature or enhancement

The auto import says "Auto-Complete", whereas the native PyCharm import lists the path (e.g. src.utils). When importing something that can be imported from several files that's unpractical. When selecting it a box pops up that lists where the import is coming from but that's a way slower UX than seeing it directly in the autocomplete popup.

### Proposed solution

Put the import path directly in the autocomplete popup instead of "Auto-Import".

**Comment by InSyncWithFoo** [comment]
Here's how an auto-import completion item looks like:

```json5
{
	"result": {
		"items": [
			{
				"label": "no_type_check", "kind": 3,
				"data": {
					"uri": "file:///<project>/file.py",
					"position": { "line": 5, "character": 13 },
					"autoImportText": "```\nfrom typing import no_type_check\n```",
					"symbolLabel": "no_type_check"
				},
				"sortText": "12.9999.no_type_check.06.typing",
				"detail": "Auto-import",
				"labelDetails": { "description": "typing" },
				"documentation": {
					"kind": "markdown",
					"value": "```\nfrom typing import no_type_check\n```"
				},
				"textEdit": {
					"range": {
						"start": { "line": 5, "character": 0 },
						"end": { "line": 5, "character": 13 }
					},
					"newText": "no_type_check"
				},
				"additionalTextEdits": [
					{
						"range": {
							"start": { "line": 0, "character": 0 },
							"end": { "line": 0, "character": 0 }
						},
						"newText": "from typing import no_type_check\n\n\n"
					}
				]
			},
            // ...
		],
		"isIncomplete": true
	}
}
```

It seems that auto-import completions always have a `.data` property which itself has an `.autoImportText` property that holds the Markdown-formatted import statement. I'll be using this as the guard. Checking that `detail == "Auto-import"` is rather l10n-unfriendly, so that's not an option.

**Comment by johannesschaffer** [comment]
I didn't quite understand the last sentence but from the rest I got that it's possible to put the path instead of "Auto-Import", right?

**Comment by InSyncWithFoo** [comment]
@johannesschaffer What I mean is that Pyright's messages are [localized](https://github.com/microsoft/pyright/tree/d1515002d90631a83990eaac4e796c78737a3405/packages/pyright-internal/src/localization). The message may be "*Auto-import*", but it can also be, say, "*[Automatický import](https://github.com/microsoft/pyright/blob/d1515002d90631a83990eaac4e796c78737a3405/packages/pyright-internal/src/localization/package.nls.cs.json#L13C30-L13C48)*".

**Comment by johannesschaffer** [comment]
@InSyncWithFoo Would be great if you could parse it to only get the path (like VSCode does). The format in `autoImportText` seems to be "from {path} import {name}". So you can split it by white space and take the second entry

**Comment by InSyncWithFoo** [comment]
@johannesschaffer No, `autoImportText`'s value is not used to extract the source (it is provided directly in `.labelDetails.description`); I used it only as a way to differentiate auto-import completions from other completions. See the PR.
