### ISSUE TITLE
"IllegalStateException: Missing header Content-Length in input" on Windows

### ISSUE THREAD

**Issue by InSyncWithFoo** [InSyncWithFoo/pyright-langserver-for-pycharm#5]
See [this comment](https://github.com/InSyncWithFoo/pyright-experimental-plugin/issues/1#issuecomment-1975090694). This issue is used to track the debugging progress.

**Comment by InSyncWithFoo** [comment]
Pyright seems to be churning out 2+ messages in just one go, and [the handling method](https://github.com/eclipse-lsp4j/lsp4j/blob/527f4c0c0c4b69e58d8e0c29c89cd64c32147f22/org.eclipse.lsp4j.jsonrpc/src/main/java/org/eclipse/lsp4j/jsonrpc/json/StreamMessageProducer.java#L67) is messing up somehow. Having spending at least a few hours to read it, I think it ought to have been written in a more readable and [SRP](https://en.wikipedia.org/wiki/Single_responsibility_principle)-conforming manner.

Since I'm too much of an idiot to make heads or tails from [the specs](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification) alone, I'm writing prototype plugins for other similar CLI language servers to see whether this is expected or not.

P/S: By the way, the specs [says that](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#baseProtocol) `\r\n` is expected after each header line and the whole header, yet there is no `\r` in Pyright's response. Reproducible example: `pip install pyright`, then run [this script](https://gist.github.com/InSyncWithFoo/e49a575fef7876ff3a9d531739c2780b).

**Comment by InSyncWithFoo** [comment]
Wrote a plugin for [`lua-language-server`](https://github.com/LuaLS/lua-language-server), got the same errors. Changed my shell to WSL (Ubuntu) using <b>Tools | Terminal</b>, but that doesn't seem to do anything.

Two possibilities left:

* There is something wrong with Windows, or
* There is something wrong with my machine.

Given my own and Microsoft's history of doing weird things, I'd say these two are equally likely.
Regardless, I truly hope it's the second, since finding a fix would otherwise be too much for my sleeping schedule.

**Comment by InSyncWithFoo** [comment]
<em><i>Eureka</i>!</em> I found it:

```diff
-GeneralCommandLine(executable.canonicalPath, "--stdio")
+GeneralCommandLine(executable.canonicalPath, "--stdio").withCharset(Charsets.UTF_8)
```

This means whatever shell in used is not using UTF-8, and that would be the default PowerShell 5 (possibly) with its Windows-1252 encoding:

![image](https://github.com/InSyncWithFoo/pyright-experimental-plugin/assets/122007197/19f91bd7-f0c5-458c-9fb5-5fe46e0d4f48)

I'm not sure why PS 5 was used. I have been using Windows Terminal for some time and the default is shown as <i>PowerShell</i> (black-ish logo) instead of <i>Windows PowerShell</i> (blue logo), which uses UTF-8 according to `[System.Text.Encoding]::Default`.

Thanks Microsoft for making this easy to fix. Oh wait, it's their fault in the first place.

A fix is coming. Right after I get some rest.

**Comment by martijnthe** [comment]
Great sleuthing!
