### ISSUE TITLE
Deprecating this plugin

### ISSUE THREAD

**Issue by InSyncWithFoo** [InSyncWithFoo/pyright-langserver-for-pycharm#60]
As I have partially explained in #57, I intend to deprecate this plugin and migrate all of its features to [its sister](https://github.com/InSyncWithFoo/pyright-for-pycharm). 

I have been maintaining them for about 4 months now, and the experience so far is not quite good. Repeating <em>almost</em> everything twice is terribly tedious. I know I have made a mistake publishing them both. I know I should not ask my users to waste their time on something which should have been done without them noticing. I'm sorry.

To fix this problem, I'll merge them into one and archive this repository for good. Users should migrate to the new plugin going forward. Until that becomes a reality, I'll continue to keep this plugin alive. There will be no other major releases.

In case someone wants to keep using this plugin, releases from [v1.0.0](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/releases/tag/v1.0.0) and later will be installable on 2024.1 and all later versions, regardless of whether they are truly incompatible or not.

**Comment by ReHoss** [comment]
> As I have partially explained in #57, I intend to deprecate this plugin and migrate all of its features to [its sister](https://github.com/InSyncWithFoo/pyright-for-pycharm).
> 
> I have been maintaining them for about 4 months now, and the experience so far is not quite good. Repeating _almost_ everything twice is terribly tedious. I know I have made a mistake publishing them both. I know I should not ask my users to waste their time on something which should have been done without them noticing. I'm sorry.
> 
> To fix this problem, I'll merge them into one and archive this repository for good. Users should migrate to the new plugin going forward. Until that becomes a reality, I'll continue to keep this plugin alive. There will be no other major releases.
> 
> In case someone wants to keep using this plugin, releases from [v1.0.0](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm/releases/tag/v1.0.0) and later will be installable on 2024.1 and all later versions, regardless of whether they are truly incompatible or not.

I have both installed, I thought they were complementary lol.
@InSyncWithFoo , should I safely delete this one now?

**Comment by InSyncWithFoo** [comment]
> I have both installed, I thought they were complementary lol

I am... not so glad to inform you that this might cause minor problems for the configuration migrators, in the case you have custom settings for both of them. Worst case, you will have to migrate a few old settings manually if you want those back (you can find them in `.idea/pyright.xml`, `.idea/pyright-langserver.xml` and [the IDE's configuration directory](https://www.jetbrains.com/help/pycharm/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory)).

As the creator, this is my blame to take, for which I have just suffered the divine punishment of rewriting some 4000 LOC; I could only hope for your forgiveness.

> [...] should I safely delete this one now?

If you don't mind, would you like to try out the new build <em>right now</em>? If you do, uninstall both, then download the new build from [here](https://github.com/InSyncWithFoo/pyright-for-pycharm/actions/runs/11956235999) (scroll to <i>Artifacts</i> at the bottom of the page) and [install it manually](https://www.jetbrains.com/help/pycharm/managing-plugins.html#install_plugin_from_disk). <b>Important</b>: Restart the IDE to make sure the migrators run.

**Comment by ReHoss** [comment]
> > I have both installed, I thought they were complementary lol
> 
> I am... not so glad to inform you that this might cause minor problems for the configuration migrators, in the case you have custom settings for both of them. Worst case, you will have to migrate a few old settings manually if you want those back (you can find them in `.idea/pyright.xml`, `.idea/pyright-langserver.xml` and [the IDE's configuration directory](https://www.jetbrains.com/help/pycharm/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory)).
> 
> As the creator, this is my blame to take, for which I have just suffered the divine punishment of rewriting some 4000 LOC; I could only hope for your forgiveness.
> 
> > [...] should I safely delete this one now?
> 
> If you don't mind, would you like to try out the new build _right now_? If you do, uninstall both, then download the new build from [here](https://github.com/InSyncWithFoo/pyright-for-pycharm/actions/runs/11956235999) (scroll to Artifacts at the bottom of the page) and [install it manually](https://www.jetbrains.com/help/pycharm/managing-plugins.html#install_plugin_from_disk). Important: Restart the IDE to make sure the migrators run.

No worries, the plugin is very good, and when I say "complementary". I mean, I thought both had specific features. I do not use any specific config (except a `pyrightconfig.json` file).
I may try your build soon!

**Comment by CoreJa** [comment]
Hi @InSyncWithFoo , I'm a new user of you plugin, currently trying my best to figure out if this plugin has been merged to its [sister repo](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm). I can see there's a [PR](https://github.com/InSyncWithFoo/pyright-for-pycharm/issues/77) that looks like it, and it is closed. But I'm also seeing that this issue has not been closed, nor does this repo has been archived.

I'm not pushing or anything, please don't feel any pressure. I'm just trying ask 2 things:
- Is the [sister repo](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm) the main plugin now?
- Does it(its sister) supports [LSP API](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html)?

If the answers to these two questions are yes, perhaps it would be better to update some docs and README stuff. Just one line in the **main** repo would be great: _features from `pyright-langserver-for-pycharm` has been already merged here_.

Appreciate your work!

**Comment by CoreJa** [comment]
My apologies, I can tell that those 2 questions are answered and they are YES. I just started used the main plugin and LSP stuff is right there. I also see docs that say migrate stuff. Sorry about the messages above.

> Hi @InSyncWithFoo , I'm a new user of you plugin, currently trying my best to figure out if this plugin has been merged to its [sister repo](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm). I can see there's a [PR](https://github.com/InSyncWithFoo/pyright-for-pycharm/issues/77) that looks like it, and it is closed. But I'm also seeing that this issue has not been closed, nor does this repo has been archived.
> 
> I'm not pushing or anything, please don't feel any pressure. I'm just trying ask 2 things:
> 
> * Is the [sister repo](https://github.com/InSyncWithFoo/pyright-langserver-for-pycharm) the main plugin now?
> * Does it(its sister) supports [LSP API](https://plugins.jetbrains.com/docs/intellij/language-server-protocol.html)?
> 
> If the answers to these two questions are yes, perhaps it would be better to update some docs and README stuff. Just one line in the **main** repo would be great: _features from `pyright-langserver-for-pycharm` has been already merged here_.
> 
> Appreciate your work!

**Comment by InSyncWithFoo** [comment]
@CoreJa No worries! It's confusing to leave both lying around, indeed.

This repository is effectively archived. I'll see if I could publish the last release within this week or the next to end its life for good.
