### ISSUE TITLE
Allow Locale Configuration for Pyright Output Messages

### ISSUE THREAD

**Issue by otsuka** [InSyncWithFoo/pyright-langserver-for-pycharm#74]
### Feature or enhancement

I am using the pyright-langserver-for-pycharm plugin on mac with IntelliJ. While Pyright provides diagnostic messages in multiple languages, it currently relies on the system-wide locale settings to determine the language of these messages. I would like to configure the language of Pyright's output messages independently of the system-wide locale settings, as changing the system locale is not always desirable or practical.

### Proposed solution

I propose adding a feature to the pyright-langserver-for-pycharm plugin that allows users to configure the locale for Pyright's output messages directly within the IDE. This could be implemented as a settings option in the plugin, where users can specify the desired locale for diagnostic messages without affecting the system-wide locale settings on mac or other operating systems. This would offer greater flexibility for developers who work in multilingual environments or prefer to see error messages in a specific language.

### Additional context

https://github.com/microsoft/pyright/blob/main/docs/configuration.md#locale-configuration

**Comment by InSyncWithFoo** [comment]
Done. Try the fix out and let me know if it works for you.

**Comment by otsuka** [comment]
@InSyncWithFoo 
Thank you so much for the quick response and implementation! I’ve tried out the new build, and it works perfectly. The ability to configure the locale for Pyright’s output messages directly within the IDE is exactly what I needed. I really appreciate your prompt attention to this feature request and the excellent work in delivering it.

Thanks again for your support and for making this enhancement happen!
